services:
  mongodb:
    image: mongo:7
    container_name: moc-home-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - moc_mongo_data:/data/db

volumes:
  moc_mongo_data:
